### ISSUE TITLE
SimpleNetVar clean up and documentation

### ISSUE THREAD

**Issue by graphanalytics** [NCBI-Hackathons/Network_SNPs#10]
As per the directory structure, clean up things in simplenetvar folder.
Document how it was installed, detailing any custom code modifications, issues found and fixed (as a README or in similar file), any custom alternative approaches followed to make the tool running, that is not described in the existing documentation.

**Comment by oscarlr** [comment]
Done. I finished documenting README file. All the SimpleNetVar scripts(2) are in the scripts folder and they are documented.

**Comment by hagenaue** [comment]
Awesome. Can you look over the paper too?
I think there is one question specifically addressed to you:

"According to the GeneMania documentation, it can include more than just
protein-protein interactions. Are we sure only PPIs were included in the
GeneMania network that we downloaded? "

On Mon, Jan 18, 2016 at 4:02 PM, oscarlr notifications@github.com wrote:

> Done. I finished documenting README file. All the SimpleNetVar scripts(2)
> are in the scripts folder and they are documented.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/NCBI-Hackathons/Network_SNPs/issues/10#issuecomment-172653113
> .

## 

Megan Hastings Hagenauer, Ph.D.

Research Investigator in the Molecular, Behavioral Neuroscience Institute
Instructor in the Department of Psychology
University of Michigan-Ann Arbor

**Comment by hagenaue** [comment]
Ah - good question:  The paper is located on Google Docs.  It is called
"Network".

On Mon, Jan 18, 2016 at 4:20 PM, Oscar Rodriguez olrodriguez01@gmail.com
wrote:

> VJ created/downloaded the network. And yeah, the network only contained
> PPIs.
> 
> But where can I find the paper again?
> 
> On Jan 18, 2016, at 4:06 PM, Megan Hagenauer notifications@github.com
> wrote:
> 
> Awesome. Can you look over the paper too?
> I think there is one question specifically addressed to you:
> 
> "According to the GeneMania documentation, it can include more than just
> protein-protein interactions. Are we sure only PPIs were included in the
> GeneMania network that we downloaded? "
> 
> On Mon, Jan 18, 2016 at 4:02 PM, oscarlr notifications@github.com wrote:
> 
> > Done. I finished documenting README file. All the SimpleNetVar scripts(2)
> > are in the scripts folder and they are documented.
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > <
> > https://github.com/NCBI-Hackathons/Network_SNPs/issues/10#issuecomment-172653113
> > 
> > .
> 
> ## 
> 
> Megan Hastings Hagenauer, Ph.D.
> 
> Research Investigator in the Molecular, Behavioral Neuroscience Institute
> Instructor in the Department of Psychology
> University of Michigan-Ann Arbor
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/NCBI-Hackathons/Network_SNPs/issues/10#issuecomment-172653844
> .

## 

Megan Hastings Hagenauer, Ph.D.

Research Investigator in the Molecular, Behavioral Neuroscience Institute
Instructor in the Department of Psychology
University of Michigan-Ann Arbor
