### ISSUE TITLE
dmGWAS clean up and documentation

### ISSUE THREAD

**Issue by graphanalytics** [NCBI-Hackathons/Network_SNPs#11]
As per the directory structure, clean up things in dmgwas.
Document how it was installed, detailing any custom code modifications, issues found and fixed (as a README or in similar file), any custom alternative approaches followed to make the tool running, that is not described in the existing documentation.

**Comment by hagenaue** [comment]
And, of course, actually upload clean code that can be integrated into the
rest of the program...

On Thu, Jan 7, 2016 at 1:43 PM, graphanalytics notifications@github.com
wrote:

> Assigned #11 https://github.com/NCBI-Hackathons/Network_SNPs/issues/11
> to @hagenaue https://github.com/hagenaue.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/NCBI-Hackathons/Network_SNPs/issues/11#event-508585016
> .

## 

Megan Hastings Hagenauer, Ph.D.

Research Investigator in the Molecular, Behavioral Neuroscience Institute
Instructor in the Department of Psychology
University of Michigan-Ann Arbor

**Comment by nyetsche** [comment]
This is `diff` output between the original copy of dmGWAS and the version patched yesterday:

https://github.com/NCBI-Hackathons/Network_SNPs/blob/master/dmGWAS.diff

If you're unfamiliar with `diff` or `patch`, it creates text file(s) that show the differences between two files (or files in directories) that can be interpreted by the `patch` program.

Which means:

```
wget http://bioinfo.mc.vanderbilt.edu/dmGWAS/dmGWAS_3.0.tar.gz
tar zxf dmGWAS_3.0.tar.gz
patch -p0 < dmGWAS.diff
```

should work, with the `dmGWAS/` directory now containing those fixes.

NB: for some reason this my version of `patch` on OSX 10.10.5 doesn't work with this diff file, but it _does_ work on the Linux instance we've been using (Ubuntu 14.04).

**Comment by graphanalytics** [comment]
done
