### ISSUE TITLE
All dmGWAS-related code now functional

### ISSUE THREAD

**Issue by hagenaue** [NCBI-Hackathons/Network_SNPs#16]
Hi everyone,
All of the dmGWAS code is now functional and uploaded to github (with names starting Bash1-4). 
I believe it is reasonably well-annotated now, but was thinking that it would be helpful to include information about dependencies. Should this go in the code annotation, someplace on github (if so, where?), or both?
Also, how do I integrate it with what has already been made?  (or just leave this up to Eric?)
Thanks!
Megan

**Comment by DCGenomics** [comment]
You guys are all awesome!

Cheers!

Ben

**Comment by RadixSeven** [comment]
I should probably do the integration, but it will take me a few days until I can get to it. 

```
On Sunday, January 10, 2016 10:30 PM, DCGenomics <notifications@github.com> wrote:
```

 You guys are all awesome!

Cheers!

Ben

**Comment by hagenaue** [comment]
hmm... or perhaps I am not quite done:
Apparently part of the reason that the output from dmGWAS_3.0 didn't match the documentation is because I chose to use a version of it that did not require that differential co-expression data be provided in order to provide weight for the edges in the network.  This caused the function to default back to the output provided by dmGWAS_2.0 (and described in http://bioinfo.mc.vanderbilt.edu/dmGWAS/V2.3/dmGWAS_Documentation_v2.pdf), which can be extracted using functions from dmGWAS_2.0 (only some of which currently still work within the current version of R and using the code package igraph).  This is why all of the syntax provided for parsing the output from the documentation for dmGWAS_3.0 didn't work with our output.

... so here are my questions for you:

1) Should I change my current code to be more efficient by using the actual provided output parsing functions instead of my own home-brewed ones?

2) The old dmGWAS (dmGWAS_2.0) actually provides a mechanism for assigning a p-value to subnetworks using permutated association files generated by PLINK.  This seems... rather important... but the directions for actually running the permutations are sketchy and seem to imply returning to the original dataset (vs. the SNP association file). We... do not have access to the original dataset for our test run... and this generally seems outside the scope of the capabilities of our pipeline. Do you agree?

**Comment by graphanalytics** [comment]
My suggestion for (1) is that... only do things that takes least amount of effort to have the pipeline working. You could create a github issue for the "efficient" code, that some day some one could pick up.

(2) is definitely outside the scope for this version of the pipeline.

**Comment by RadixSeven** [comment]
I agree. Our focus is on correctness and solution delivery. The only efficiency we need is that an extremely tiny test network (as small as possible) can finish within 30 min (so we can verify that all the steps connect together). Efficiency beyond that is nice-to-have but not essential at this point. 

```
On Monday, January 11, 2016 3:13 PM, graphanalytics <notifications@github.com> wrote:
```

 My suggestion for #1 is that... only do things that takes least amount of effort to have the pipeline working. You could create a github issue for the "efficient" code, that some day some one could pick up.#2 is definitely outside the scope for this version of the pipeline.—

**Comment by graphanalytics** [comment]
Tests complete. All tests successful.
