### ISSUE TITLE
README: Almost finished, please double check my work.

### ISSUE THREAD

**Issue by hagenaue** [NCBI-Hackathons/Network_SNPs#17]
Greetings gentleman,
I filled in all of the blanks in our github README file using either re-phrased information from our proceedings manuscript or direct quotations from the websites hosting each of the tools.  

_Please double check my work_  - perhaps each of you could respond to this message with your initials as confirmation once you have determined that the documentation for your respective tools looks correct?

Also: Is it sufficient to cite our (to-be-created) Amazon instance for all dependencies or should we actually compile a full list of dependencies within the README documentation (eek!  I think there are 7 for dmGWAS alone!!!)

Cheers,
Megan

**Comment by nyetsche** [comment]
> Is it sufficient to cite our (to-be-created) Amazon instance for all dependencies or should we actually compile a full list of dependencies within the README documentation (eek! I think there are 7 for dmGWAS alone!!!)

While there's no immediate intention to delete the Amazon image (not instance - instance is the server running at a single duration of time, image is the "physical" bytes that can reproduce an instance), I wouldn't consider it reliable for documentation, long-term. It can go away, get renamed, and even if it doesn't, a curious user would have to play "software archeology" to figure out what components went into it.

...unfortunately that means the archeology falls on us authors. There's a document in the Google folder called 'software manifest', but for the R/Python parts, all the images used:

```
/opt/biobuilds - Biobuilds 2015.11 using Anaconda/Conda
https://github.com/lab7/biobuilds/blob/master/Release-Notes-2015.11.md
R 3.2.2
.libPaths(): /opt/BioBuilds-2015.11/lib/R/library
BioConductor base 3.0
Python 2.7.10 (from Ananconda)
```

_If_ you installed a lot of other R libraries or Python libraries, we'd have to dig those out too. 

http://www.r-bloggers.com/list-of-user-installed-r-packages-and-their-versions/
And for Python (most likely): `pip freeze`

**Comment by graphanalytics** [comment]
Made small changes.

**Comment by graphanalytics** [comment]
Manuscript completed.
