### ISSUE TITLE
How will others log in on the new ami?

### ISSUE THREAD

**Issue by RadixSeven** [NCBI-Hackathons/Network_SNPs#7]
Right now the machine only lets people with our private keys log in. We want anyone to be able to log in (and then have to change the password or something). I'm sure there is a standard way of doing this. This issue is to find that way and implement it.

**Comment by graphanalytics** [comment]
I am expecting that we would be working on this instance for some time. So, we would need the keys in place as such so we can continue working. 
Considering this, and also that we need to have an AMI available to be quoted in the manuscript, I propose that we create another instance of the machine that we have running now. Clean up the keys in the newly created instance and create an AMI using that instance. We could point this instance in our manuscript.

**Comment by nyetsche** [comment]
AWS has the concept of an 'image' (or "AMI") and an instance. An instance is currently running server, based off an image, which then diverges.

We'll keep your instance up for a few more days, but what we'll do is create an image _from your running instance_. It'll have all the software, directories, etc., exactly as-is. (I will clean out your SSH keys before doing so).

Then, anyone can start their own _instance_, from that _image_. The image has software built-in that will let the user log in with their own, personal SSH keys.

So to be clear: in the manuscript, you're going to want to refer to the image, not the instance.

**Comment by RadixSeven** [comment]
So the image does not record information on login permissions etc, I had assumed that it did and that one needed to distribute some kind of initial authentication with an image. That explains why amazon needed their own format.

```
On Thursday, January 7, 2016 11:24 AM, Matthew Lesko <notifications@github.com> wrote:
```

 AWS has the concept of an 'image' (or "AMI") and an instance. An instance is currently running server, based off an image, which then diverges.We'll keep your instance up for a few more days, but what we'll do is create an image from your running instance. It'll have all the software, directories, etc., exactly as-is. (I will clean out your SSH keys before doing so).Then, anyone can start their own instance, from that image. The image has software built-in that will let the user log in with their own, personal SSH keys.So to be clear: in the manuscript, you're going to want to refer to the image, not the instance.—
